### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by smaragdus** [zhongyang219/ColorPicker#1]
I don't speak Chinese yet I had a look at **ColorPicker** and I liked its simplicity. So I will appreciate if the program is translated into English. Since the program is not very big I suppose the translation would not require too much work.

**Comment by zhongyang219** [comment]
Hello, I‘m Sorry I haven't seen this issue. English support has been added now, you can download the latest release version (V1.32).

**Comment by smaragdus** [comment]
@zhongyang219 

Thank you translating your [ColorPicker](https://github.com/zhongyang219/ColorPicker) into English! I downloaded version [1.32](https://github.com/zhongyang219/ColorPicker/releases/tag/V1.32) and did a brief testing. Everything seems fine with the exception that the information in the **About** window is not updated to the latest version, it still shows version **1.31**, screen:

![ColorPicker 1 32 - 2020-08-05 - error - 001](https://user-images.githubusercontent.com/9025757/89434027-bb1d4c80-d74b-11ea-875e-327ce7b09acc.png)

However the file version is correct- **1.3.2.0**.

I am glad that your colour picker is portable as settings are saved in **color_table.ini** file in program folder.

Since the program is now available in English I will close this issue. I may suggest some tiny enhancements in the future.

I use two of your other programs- [MusicPlayer2](https://github.com/zhongyang219/MusicPlayer2) and [TrafficMonitor](https://github.com/zhongyang219/TrafficMonitor), I was impressed and that was why I got interested in [ColorPicker](https://github.com/zhongyang219/ColorPicker)- I am not a programmer but I can appreciate good programming and I like the fact that you use a nice programming language- **C++**, as I am totally fed up with **JavaScript**/**Electron** junk which is conquering the desktop right now.

Best regards

**Comment by zhongyang219** [comment]
I forgot to modify the version information in the English version. It has been modified now.

**Comment by smaragdus** [comment]
@zhongyang219 

I re-downloaded it and it shows the correct version, thanks. I noticed that it also shows x64 version in 'About' windows when x64 version is used.
